ArcTareas/ArcTareas/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('api/',include('api.urls')),
    path('',include('cuenta.urls')),
    path('admin/', admin.site.urls),
    path('tarea/',include('tarea.urls',namespace='tarea')),
    path('accounts/',include('cuenta.urls')),
  

]

ArcTareas/api/urls.py
from django.urls import path
from api.views import listTarea,crearTarea

urlpatterns = [
    path('list/',listTarea,name='list'),
    path('create/',crearTarea,name='create'),   
]

ArcTareas/tarea/urls.py
from django.contrib import admin
from django.urls import path,include
from tarea.views import HomeView,TareaDetailView,TareaEliminar,TareaAgregar,GuardarTiempo

app_name = "tarea"

urlpatterns = [
    path('tarea_list/',HomeView.as_view(),name='tarea_list'),
    path('tarea_detail/<int:pk>',TareaDetailView.as_view(),name="detail"),
    path('eliminar_tarea/',TareaEliminar.as_view(),name="eliminar_tarea"),
    path('agregar_tarea/',TareaAgregar.as_view(),name="agregar_tarea"),
    path('guardar_tiempo/',GuardarTiempo.as_view(),name="guardar_tiempo"),
]

ArcTareas/tarea/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tarea(models.Model):
    """Model definition for Tarea."""
    # TODO: Define fields here
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Nombre", max_length=50)
    content = models.TextField(verbose_name="Contenido")
    time = models.IntegerField(verbose_name="Tiempo de Tarea")
    created = models.DateTimeField(verbose_name="Fecha de creacion",auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Fecha de actualizacion",auto_now=True)

    class Meta:
        """Meta definition for Tarea."""

        verbose_name = 'Tarea'
        verbose_name_plural = 'Tareas'
        ordering = ['created']

    def __str__(self):
        """Unicode representation of Tarea."""
        return self.name

ArcTareas/tarea/forms.py
from django import forms

class TareaForm(forms.Form):
    name = forms.CharField(label="name",max_length=250)
    content = forms.CharField(max_length=250)

ArcTareas/tarea/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from tarea.models import Tarea
from django.http import JsonResponse
from tarea.forms import TareaForm
# Create your views here.

@method_decorator(login_required, name='dispatch')
class HomeView(TemplateView):
    template_name = "tarea/home.html"

    def get_context_data(self,*args,**kwargs):
        tareas = Tarea.objects.filter(user__username=self.request.user)
        return {'tareas':tareas}


@method_decorator(login_required, name='dispatch')
class TareaDetailView(DetailView):
    model=Tarea
    template_name = "tarea/tarea_detail.html"

class TareaEliminar(TemplateView):
    
    def post(self,request,*args,**kwargs):
        pk = request.POST['identificador']
        print(pk)
        tarea = Tarea.objects.get(pk=pk)
        tarea.delete()
        response = {}
        return JsonResponse(response)

class TareaAgregar(TemplateView):
    def post(self,request,*args,**kwargs):
        name = request.POST['name']
        content = request.POST['content']
        tarea = Tarea.objects.create(user=self.request.user,
                                     name=name,content=content,time=0)
        response = {}
        return JsonResponse(response)

class GuardarTiempo(TemplateView):
    def post(self,request,*args,**kwargs):
        tiempo = request.POST['tiempo']
        id_tarea = request.POST['id_tarea']
        tarea = Tarea.objects.get(pk=id_tarea)
        tarea.time = tarea.time + int(tiempo)
        tarea.save()
        response = {}
        return JsonResponse(response)

ArcTareas/tarea/templates/tarea/home.html
{% extends "cuenta/base.html" %}
{% block title %} Home {% endblock title %}
{% block subtitle %} Gestor Tareas {% endblock subtitle %}
{% block content %}

<!-- Modal que se activa con el boton mas(Agregar Tarea) -->
    <div id="modal1" class="modal">
            <div class="modal-content">
                <h4>Añadir Tarea</h4>
                <div class="row">
                    <form class="col s12" name="formulario" id="formulario">
                        <div class="row modal-form-row">
                            <div class="input-field col s12">
                                <input id="nombre" type="text" name="name" class="validate">
                                <label for="nombre">Nombre</label>
                            </div>
                        </div>    
                        <div class="row">
                            <div class="input-field col s12">
                                <textarea id="contenido" type="text" name="content" class="materialize-textarea validate"></textarea>
                                <label for="contenido">Contenido</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a onclick="agregar()" class=" modal-action modal-close waves-effect waves-green btn">Aceptar</a>
                            <a class=" modal-action modal-close waves-effect waves-green btn">Cancelar</a>
                        </div>             
                    </form>
                </div>
            </div>
    </div>
    <!-- Cuerpo principal del html -->
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
        <h1 class="header center orange-text">Tareas</h1>
        <div class="row center">
            <h5 class="header col s12 light">Gestiona de forma practica tus tareas</h5>
        </div>
        <br><br>
        </div>
    </div>
    <div class="container">
        {% for tarea in tareas %}
            <ul class="collection with-header">
                <li style="background:#F6F6F6;" class="collection-item">
                    <a href="{% url 'tarea:detail' tarea.id %}">
                        {{tarea.name}}
                        <a  onclick="eliminarTarea('{{ tarea.id }}')"  class="secondary-content">
                             <i  style="color:#ff9800" class="material-icons">delete</i>
                        </a>
                    
                    </a>
                </li>
            </ul> 
        {% endfor %}
    </div>
    <!-- Boton Agregar tareas-->
    <div class="fixed-action-btn">
        <a class="btn-floating pulse btn-large waves-light orange modal-trigger" data-target="modal1"><i class="material-icons">add</i></a> 
    </div>
    
{% endblock content %}

{% block script %}
    <script>
        $(document).ready(function(){
            $('.modal').modal();
        });
        function eliminarTarea(identificadorId) {
            var request = $.ajax({
                type: "POST",
                url: "{% url 'tarea:eliminar_tarea' %}",
                data: {
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                    "identificador": identificadorId                    
                },
            });
            request.done(function(response) {
                location.reload();
            });
        }
        function agregar(){
            console.log(formulario.name.value.length)
            if(formulario.name.value.length == '0' || formulario.content.value.length == '0')
            {
                alert("Campos vacios");
            }
            else{
                name = formulario.name.value;
                content = formulario.content.value;
                var request = $.ajax({
                    type: "POST",
                    url: "{% url 'tarea:agregar_tarea' %}",
                    data: {
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                        "name": name,
                        "content":content,    
                    },
                });
               
                request.done(function(response) {
                    location.reload();
                });

            }
           
        }
    </script> 

{% endblock script %}
    

ArcTareas/tarea/templates/tarea/tarea_detail.html
{% extends "cuenta/base.html" %}
{% block title %} Detalle {% endblock title %}
{% block subtitle %} Detalle Tarea {% endblock subtitle %}

{% block regresar %}
    <a onclick="guardarDato();" id="logo-container" href="#" class="brand-logo" style="left:2%;">
        <i style="color:aliceblue; font-size:100%;" class="material-icons prefix">arrow_back</i>
    </a>
{% endblock regresar %}
    
{% block content %}

    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
        <h1 class="header center orange-text">Tarea #{{tarea.id}}</h1>
        </div>
    </div>
    <div class="container">
        <div class="section">
            <div class="col s12 m7 dark">
                <h2 class="header"><b>{{tarea.name}}</b></h2>
                <div class="card horizontal">
                    <div class="card-stacked ">
                        <div>
                            <p>{{tarea.content}}</p>
                        </div>
                        <div class="card-action center">
                            <div id="contenedor1">
                                <input type="hidden" id="dato" value="{{tarea.time}}">
                                <input type="hidden" id="id_tarea" value="{{tarea.id}}">
                                <div class="reloj" id="Horas"></div>
                                <div class="reloj" id="Minutos"></div>
                                <div class="reloj" id="Segundos"></div>
                            </div>
                        </div>
                        <div class="card-action center">
                            <button style="border-radius: 100px;" id="inicio" value="Start" onclick="inicio();"><i class="material-icons">play_arrow</i></button>
                            <button style="border-radius: 100px;" id="parar" value="Stop" onclick="parar();" disabled><i class="material-icons">pause</i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script>
            window.onload = datos();
            function datos () {
                tiempoTarea = document.getElementById('dato').value
                centesimas = 0;
                segundos = Math.floor(tiempoTarea % 60);
                if (segundos < 10){
                    segundos = "0"+segundos;
                }
                minutos = Math.floor(tiempoTarea / 60);
                if (minutos < 10){
                    minutos = "0"+minutos;
                }
                horas = Math.floor(tiempoTarea / 3600);
                if (horas < 10){
                    horas = "0"+ horas;
                }
                Segundos.innerHTML = ":" + segundos;
                Minutos.innerHTML = ":" + minutos;
                Horas.innerHTML = horas;
            }

            function guardarDato(){
                tiempo = tiempoTareafinal
                id_tarea = document.getElementById('id_tarea').value
                var request = $.ajax({
                    type: "POST",
                    url: "{% url 'tarea:guardar_tiempo' %}",
                    data: {
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                        "id_tarea": id_tarea,
                        "tiempo":tiempo,                
                    },
                });
                request.done(function(response) {
                        window.location.replace("{% url 'tarea:tarea_list' %}");
                  
                });
            }
            function parar () {
                clearInterval(control);
                document.getElementById("parar").disabled = true;
                document.getElementById("inicio").disabled = false;

            }
            
    </script>
{% endblock script %}